### ISSUE TITLE
proposal: Importfile

### ISSUE THREAD

**Issue by matti** [importpw/import#32]
Proposal: `Importfile` which works a bit like `Gemfile`:

```
#!/usr/bin/env import

# The URL is downloaded once, cached forever, and then sourced
import "https://git.io/fAWiz"
```

And then calling `import install`  would download&cache files. This would be great for docker builds.

**Comment by emiliovesprini** [comment]
How would
`Importfile` + `import install`
differ from
`imports.sh` + `./imports.sh`
?

**Comment by matti** [comment]
It wouldn't - it would just be nice and tasty sugar.

**Comment by TooTallNate** [comment]
There's nothing stopping you from naming the file that, but I don't see what `import install` would do. You could simply do `import Importfile` or make the Importfile be executable and run `./Importfile` to achieve the same effect.

**Comment by emiliovesprini** [comment]
😂😂😂
`./imports/import/import.sh importyMcImportsface.sh`

**Comment by matti** [comment]
So this is an documentation issue for the readme as a "how to make sure your imports are loaded and this thing actually makes sense for production"
