### ISSUE TITLE
Default $IMPORT_CACHE creates $HOME folder bloat

### ISSUE THREAD

**Issue by emiliovesprini** [importpw/import#36]
Peppering $HOME with hidden files and folders is a generally agreed upon anti-pattern (check [here](https://0x46.net/thoughts/2019/02/01/dotfile-madness/) or [here](https://zdsfa.com/insert/blog/a-guide-to-home-protection/) for more info) commonly fixed with the help of the [XDG Base Directory spec](https://wiki.archlinux.org/index.php/XDG_Base_Directory).

A fix may be as easy as something like
```
-       local cache="${IMPORT_CACHE-${HOME}/.import-cache}"
+       local cache="${HOME}/.cache/import"
+       [ -n "$XDG_CACHE_HOME" ] && local cache="${XDG_CACHE_HOME}/import"
+       [ -n "$IMPORT_CACHE" ] && local cache="$IMPORT_CACHE"
```
but there's the obvious issue of backwards compatibility, so maybe this should be closed as wontfix.

**Comment by vardrop** [comment]
@emiliovesprini *```$IMPORT_CACHE```, you misspelled it in the title as ```$IMPORT_CASH```

**Comment by emiliovesprini** [comment]
Fixed, thanks.

**Comment by TooTallNate** [comment]
Ya, I'd like to support the XDG Base Directory spec. Pull request welcome if you feel like taking a stab at it, your diff looks pretty good to me already!

**Comment by emiliovesprini** [comment]
So you don't mind me changing the default dir? Be right back.

**Comment by emiliovesprini** [comment]
Having trouble making the tests pass, might take me a bit longer.

**Comment by TooTallNate** [comment]
Note that Windows and macOS have different conventions for their cache dirs. `import` should use these by default, if `$XDG_CACHE_HOME` is not defined:

* Linux: `$HOME/.cache/import`
* macOS: `$HOME/Library/Caches/import`
* Windows: `$HOME/AppData/Local/import/Cache`

**Comment by TooTallNate** [comment]
> but there's the obvious issue of backwards compatibility, so maybe this should be closed as wontfix.

Backwards compatibility isn't a concern in this case, since a cache directory by its nature is ephemeral - it would just have to re-download the cache files into the new directory.

**Comment by TooTallNate** [comment]
Open up the pull request anyways, we can work through the errors there.

**Comment by emiliovesprini** [comment]
Sorry I left you guys hanging, I got busy with school.
