### ISSUE TITLE
Updating `import`

### ISSUE THREAD

**Issue by vladimyr** [importpw/import#37]
What is the preferred way to keep your `import` installation up to date?
According to https://github.com/importpw/import/pull/1#issue-206653973, this is already v1? Do you plan to version `import` and produce tagged releases?

**Comment by TooTallNate** [comment]
> What is the preferred way to keep your `import` installation up to date?

At this time, just curling it again. The target has been to make the core `import` function be as rock-solid as possible and to never break the API, such that it will always be safe to curl the latest version of the script.

> According to https://github.com/importpw/import/pull/1#issue-206653973, this is already v1?

Disregard the description in that PR, I don't consider import to be v1 yet (not until there's a git tag!).

> Do you plan to version `import` and produce tagged releases? 

Yes, definitely. I realize that versioning is important for reliability/reproducibility purposes, so I'd like to start adding git tags very soon. `import` and all the other repositories in this org follow the semver spec.

**Comment by vladimyr** [comment]
Great, thank you for taking the time to answer my questions 👍 
I'll keep an eye on tags/releases 😉
