### ISSUE TITLE
Not working on macos

### ISSUE THREAD

**Issue by jerrygreen** [importpw/import#48]
```bash
jerrygreen@jerrygreen ~ % curl -sfLS https://import.pw > /usr/local/bin/import
chmod +x /usr/local/bin/import
jerrygreen@jerrygreen ~ % import "https://git.io/fAWiz"                    
/usr/local/bin/import: line 214: https://git.io/fAWiz: No such file or directory
```

## Preview

<img width="570" alt="Screenshot 2020-11-08 at 08 03 49" src="https://user-images.githubusercontent.com/13215662/98455947-effccd80-2198-11eb-93fd-19b4deb30d97.png">

**Comment by TooTallNate** [comment]
Hey @jerrygreen. So you're missing the part where you first have to `source` the import script into your shell.

```
curl -sfLS https://import.sh > /usr/local/bin/import
chmod +x /usr/local/bin/import
. "$(command -v import)"
import "https://git.io/fAWiz"
```

**Comment by jerrygreen** [comment]
@TooTallNate i have used official installation instructions, «Bootstrapping the import function»:

https://github.com/importpw/import/blob/master/docs/install.md#-bootstrapping-the-import-function
